# Nombre de servicio
spring:
  application:
#    name: zuul-autofin-proxy
    name: zuul-server
# Perfil
  profiles:
    active: '@appProfile@'
#Zipkin-Sleuth
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
#Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: ${SGC_URL_EUREKA:http://localhost:5601/eureka}
  #registerWithEureka: false
  #fetchRegistry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
# Check health    
management: 
  endpoints: 
    web: 
      exposure: 
#        include: 'routes'
        include: "*"

#Desabilita formulario de login
#Configura uri jwk servicio de autorizacion
security:
  basic:
    enabled: false 
  oauth2:
    resource:
      jwk:
        key-set-uri: ${SGC_URL_JWK:http://localhost:8080/auth/realms/AUTOFIN/protocol/openid-connect/certs}

#Puerto
server:
  port: ${PORT:8125}

#Setting the logging levels for the service
logging:
  level:
    org.springframework.web: WARN
    mx.com.autofin: DEBUG

# Protección de uri´s
zuul:
  routes:
    api-backend-bitacora:
      service-id: api-db-sgc
      path: /autofin/v1/bitacora/**
      stripPrefix: false
      
    api-backend-sgcadmamenu: 
      service-id: api-db-sgc
      path: /autofin/v1/sgcadmtmenu/**
      stripPrefix: false
      
    api-backend-sgcadmaroles:
      service-id: api-db-sgc
      path: /autofin/v1/sgcadmaroles/**
      stripPrefix: false
      
    api-backend-sgcadmapermisos:
      service-id: api-db-sgc
      path: /autofin/v1/sgcadmapermisos/**
      stripPrefix: false
      
    api-backend-sgcadmapermisosroles:
      service-id: api-db-sgc
      path: /autofin/v1/sgcadmapermisosroles/**
      stripPrefix: false
      
    api-backend-ldapuser:
      service-id: api-ldap
      path: /autofin/v1/userldap/**
      stripPrefix: false
      
    api-backend-sgcadmausuario:
      service-id: api-db-sgc
      path: /autofin/v1/usuario/**
      stripPrefix: false
    
    api-backend-userkeycloak:
      service-id: api-keycloak
      path: /autofin/v1/userkeycloak/**
      stripPrefix: false
      
    api-backend-userdbkeycloak:
      service-id: api-keycloak
      path: /autofin/v1/userdbkeycloak/**
      stripPrefix: false
      
    api-backend-roleskeycloak:
      service-id: api-keycloak
      path: /autofin/v1/roleskeycloak/**
      stripPrefix: false
      
    api-backend-sesionesusuario:
      service-id: api-keycloak
      path: /autofin/v1/keycloak/sesionesusuario/**
      stripPrefix: false
    
    api-keycloak-sync-ldap:
      service-id: api-keycloak
      path: /autofin/v1/keycloak/synckeycloakldap/**
      stripPrefix: false           

    api-ldap-sync-ldap:
      service-id: api-ldap
      path: /autofin/v1/ldap/synckeycloakldap/**
      stripPrefix: false
      
    api-db-firma-documento:
      service-id: api-db-firma
      path: /autofin/v1/sgcfetdocumento/**
      stripPrefix: false
    
    api-db-firma-c-tipo-documento:
      service-id: api-db-firma
      path: /autofin/v1/sgcfectipodocumento/**
      stripPrefix: false
      
    api-db-firma-receptor:
      service-id: api-db-firma
      path: /autofin/v1/sgcfetreceptor/**
      stripPrefix: false      
      
    api-efirma:
      service-id: api-efirma
      path: /autofin/v1/efirma/**
      stripPrefix: false      
       
 # ignored-services: '*'
 # prefix: /autofin/v1
  sensitive-headers: Cookie, Set-Cookie

#Timeout
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000